app/models.py
from flask_login import UserMixin
from werkzeug.security import check_password_hash, generate_password_hash

from . import db, login_manager

# Authentication of user object
'''
pass db.Model as arqument to connect our class User and allow communication btn class and db
'''
# decorate that is acallback function to handle User
# function that queries a database and get the user with id
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))
    
class User(db.Model,UserMixin):
    __tablename__ = 'users'
    
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(200), unique=True)
    email = db.Column(db.String(200))
    profile_pic_path = db.Column(db.String())
    bio = db.Column(db.String(255))
    password_secure = db.Column(db.String(300))
    
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    

    def __repr__(self):
        return f'User {self.username} {self.email} {self.password_secure}'


    @property
    def password(self):
        raise AttributeError('Cannot read paasword attribute')

    @password.setter
    def password(self,password):
        self.password_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.password_secure, password)

   

class Comment:
    '''
    Comment class to define comment object
    '''
    def __init__(self,id,name,description):
        self.id = id
        self.name = name
        self.description = description


class Role(db.Model,UserMixin):
    __tablename__ = 'roles'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200), unique=True)

    # lazy dynamic 
    users = db.relationship('User',backref = 'role',lazy="dynamic")


    def __repr__(self):
        '''
        __repr___ make easy to debug our application
        '''
        return f'Role {self.title}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import Form, TextAreaField, validators,SubmitField
import email_validator



class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',[validators.DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from config import config_options
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
# from flask_mail import Mail
# from app import db
from flask_sqlalchemy import SQLAlchemy
# from flask_uploads import IMAGES, UploadSet, configure_uploads


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.signin'
# init dabatabase
db = SQLAlchemy()
# photos = UploadSet('photos', IMAGES)
bootstrap = Bootstrap()
# mail = Mail()


def create_app(config_name):
    app = Flask(__name__)

    # app configuration
    app.config.from_object(config_options[config_name])



    # configure UploadSet
    # configure_uploads(app,photos)


    # init flask extensions for
    db.init_app(app)
    login_manager.init_app(app)
    bootstrap.init_app(app)
    # mail.init_app(app)
    
    # register our blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    #url_prefix argument that will add a prefix to all the routes registered with that blueprint.
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/authentication')


    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)


from .import views,forms

app/main/views.py
from flask import render_template
from . import main
# from .. import db,photos
from flask_login import login_required
from flask import render_template,request,redirect,abort
from .forms import UpdateProfile
from .. import db
from app.models import User




@main.route('/')
@login_required
def index():
    title = 'Pitches'

    return render_template('index.html', title=title)


@main.route('/users/<username>')
@login_required
def profile(username):
    user = User.query.filter_by(username=username).first()

    if user is None:
        abort(404)

    return render_template('profile/profile.html',user=user)

@main.route('/users/<username>/update/pic', methods=['POST'])
def update_pic(username):
    user = User.query.filter(username=username).first()

    if 'photo' in request.file:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()

    return redirect(url_for('main.profile.html',username=username))




@main.route('/users/<username>/update', methods=['GET','POST'])
# @login_required
def update_profile(username):
    user = User.query.filter(username=username).first()

    if user is None:
        abort(404)

    form = updateProfile()

    if form.validate_on_submit():
        user.bio =form.bio.data_files

        db.session.add(user)
        db.session.commit()


        return redirect(url_for('.profile',username=user.username))

    return render_template('profile/update.html',form=form)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/index.css')}}"
    />
    <title>{{title}}</title>
  </head>
  <body>
    {% block content %} {% include "navbar.html" %}{% endblock %}
      <div class=" main">
    <div class="info">
        <h3 class="title">Think.Make.<br>
            --write.pitches
        </h3>
        <p class="p-info">--- What the app do:<br>
        <span>Updvote.Downvote after reviews from users</span><br>
        In a 60second you can impress or break with someone.</p>

        <button class="btn btn-primary b-button">Contact Us</button>
    </div>
    <div class="display-content">
        {%block displayContent%}
        {%endblock%}
    </div>

  </div>
  <div class="footer">
  <p>COPYRIGHT&&2022</p>
</div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

app/templates/index.html
{% extends "base.html" %}
<h3>Hello hezron</h3>

app/templates/navbar.html
<div class="container d-flex justify-content-center">
  <div class="logo navs">
    <img src="" alt="LOGO" srcset="" />
  </div>
  <div class="navsw">
    <nav class="navbar navbar-expand-lg bg-dark text-white navs">
      <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Categories
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">PickUp line Pitch</a></li>
                <li><a class="dropdown-item" href="#">Interview Pitch</a></li>
                <li><a class="dropdown-item" href="#">Product Pitch</a></li>
                <li><a class="dropdown-item" href="#">Promotion Pitch</a></li>
              </ul>
            </li>
          </ul>
          
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a
                class="nav-link active getonright butons"
                href="{{url_for('auth.signin')}}"
                aria-current="page"
            
                >signin</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link active butons" aria-current="page" href="{{url_for('auth.signup')}}">signup</a>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
                  {% if current_user.is_authenticated %}
                  <li><a href="{{url_for('main.profile',username=current_user.username)}}">Profile</a></li>
                  <li><a href="{{url_for('auth.signin')}}">Sign in</a></li>
                  {% else %}
                  <li><a href="{{url_for('auth.signout')}}">Sign out</a></li>
                  {%endif%}
                </ul>
        </div>
      </div>
    </nav>
  </div>
</div>

app/templates/profile.html
 <div class="col-md-4">
    {% if user.profile_pic_path %}

    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

    {%else%}
    <p>No profile picture</p>

    {% endif %}

        {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',username=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
      {% endif %}
  </div>

app/templates/profile/profile.html
{% extends "base.html"%}
{% block content %}
{% if user == current_user %}
    <a href="{{url_for('main.update_profile',username=user.username)}}">Edit profile</a>
{% endif %}
<!-- displaying username -->
<h3>{{user.username | capitalize }}</h3>
<!-- displaying user bio -->
{% if user.bio %}
<p>{{user.bio}}</p>
{% else %}
<p>
  {{user.username | capitalize }} has no bio
</p>
{% endif %}

<!-- displaying picture -->
{% if user.profile_pic_path %}
<img src="{{url_for('static', filename=profile_pic_path)}}" alt="img-thumbnail">
{%else%}
<p>No profile picture</p>

{% endif %}

{% endblock %}

app/templates/profile/update.html
{% extends "base.html"%}
{% import "bootstrap/wtf.html" as wtf%}

{% block content %}
{{wtf.quick_form(form)}}
{% endblock %}

app/templates/signin.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block displayContent %}


<div class="sign">
    <!-- wtf.quick_form()  used to to render the registeration -->

        <div class="signs">{{wtf.quick_form(Form)}}</div>
</div>


{% endblock %}

app/templates/signup.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block displayContent %}


<div class="sign">
    {{wtf.quick_form(Form)}}
</div>


{% endblock %}